# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('director', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('synopsis', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('storyline', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverapp.Movie')),
                ('movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverapp.Movie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movieactor',
            unique_together=set([('movie', 'actor')]),
        ),
        migrations.AlterUniqueTogether(
            name='moviegenre',
            unique_together=set([('movie', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='moviewriter',
            unique_together=set([('movie', 'writer')]),
        ),
        migrations.AlterUniqueTogether(
            name='similarities',
            unique_together=set([('movie1', 'movie2')]),
        ),
    ]
