# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_auto_20160611_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarities',
            old_name='movie1',
            new_name='first_movie',
        ),
        migrations.RenameField(
            model_name='similarities',
            old_name='movie2',
            new_name='second_movie',
        ),
        migrations.AlterUniqueTogether(
            name='similarities',
            unique_together=set([('first_movie', 'second_movie')]),
        ),
    ]
