# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_auto_20160611_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarities',
            name='actor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='similarities',
            name='director',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='similarities',
            name='genre',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='similarities',
            name='storyline',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='similarities',
            name='synopsis',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
