# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_auto_20160612_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
    ]
